### ISSUE TITLE
The single combined .mp4 file is not available in audio/ path even after stopping the recording

### ISSUE THREAD

**Issue by Amitmahato** [aws-samples/amazon-chime-media-capture-pipeline-demo#17] opened 2021-12-02 11:55 UTC
I followed as it is told in the README. Then I have used the client side server to start the meeting and start to record the meeting. But even after stopping the recording and the meeting, I can see the chunk of .mp4 files in audio/ directory but not a single combined file. 

It seems the processLambda fails to start from CloudWatch log. The log has been attached below:

<img width="1077" alt="Screen Shot 2021-12-02 at 5 38 04 PM" src="https://user-images.githubusercontent.com/29419386/144417104-35dbb4f0-ed40-4db5-b5b1-0bcd87639b54.png">

Can someone please help me with it. I need a single video file in the S3 bucket as the final result. 
Thank you!

**Comment by achris** [comment] 2021-12-06 21:32
Hi, we have been trying to reproduce the error to see where things might have gone wrong.  As of right now it's not happening for us, but we'll keep you posted on our progress

**Comment by ajselvar** [comment] 2022-01-18 22:01
Hi @Amitmahato We are unable to reproduce this issue. Closing this issue for now. Feel free to reopen it if you see this issue again

**Closed** 2022-01-25 20:50 UTC
